#! /bin/bash
set -e

screen=""
if [ "$1" = -s ]; then
	screen=1
	shift
fi

web=""
if [ "$1" = -w ]; then
	web=1
	shift
fi

target="$1"
if [ -z "$screen" ]; then
	if [ -z "$target" ]; then
		echo "Error: target directory not specified"
		exit 1
	fi
	mkdir -p $target
	if [ "$web" ]; then
		mkdir -p $target/thumbs
	else
		arch=$(dpkg --print-architecture)
		dist=$(apt-cache policy | \
		       sed -r "/^ [0-9]+ /N; s/^ ([0-9]+) .*a=([^,]*).*/\1 \2/" | \
		       grep "^[0-9]" | sort -nru | head -n1 | awk '{print $2}')
		echo "Testset generated $(date -uR) on $arch/$dist" >$target/README
	fi
fi

gen_set() {
	count=1
	for opt in "--no-versions --no-alternatives --no-recommends" \
		   "--no-versions --no-alternatives" \
		   "--no-versions --no-alternatives --with-suggests" \
		   "--no-versions" \
		   "" \
		   "--with-suggests" \
		   "--with-suggests --versioned-conflicts" \
		   "--rotate"
	    do
		echo $1$count $1 $opt
		count=$(($count + 1))
	done
}

testset="dpkg dpkg
$(gen_set debconf)
$(gen_set aptitude)
usage1 dpkg -b --arch=all --no-recommends --no-conflicts
usage2 clamav -I -S
usage3.1 pidentd --max-providers=5
usage3.2 pidentd -I"

echo "$testset" | while read outfile package opts; do
	echo "Generating $outfile: $opts $package" >&2
	if [ "$screen" ]; then
		./debtree $opts $package | dot -Tps | kghostview - &
		sleep 10
	else
        	./debtree $opts $package >$target/$outfile.dot
		if [ "$web" ]; then
			for format in ps png svg; do
				dot -T$format -o "$target/$outfile.$format" \
					$target/$outfile.dot
			done
			# Generate thumbnail; from SVG gives best quality
			convert $target/$outfile.svg -thumbnail 400 \
				$target/thumbs/$outfile.png

			# For dpkg we only need the thumbnail
			rm -f $target/dpkg.*
			# The following files are not wanted for the website
			# because of size restraints
			rm -f $target/aptitude[5678].png
			rm -f $target/debconf[678].png
			rm -f $target/usage[12].png
			rm -f $target/usage3.[12].png
		fi
	fi
done

# Also generate the comparison graphs from apt-cache
if [ "web" ]; then
	for package in debconf aptitude; do
		outfile=${package}0
		apt-cache dotty $package >$target/$outfile.dot
		for format in ps png svg; do
			dot -T$format -o "$target/$outfile.$format" \
				$target/$outfile.dot
		done
		# Generate thumbnail; from SVG gives best quality
		convert $target/$outfile.svg -thumbnail 400 \
			$target/thumbs/$outfile.png
	done
fi
